#!/usr/bin/env python3
# SPDX-License-Identifier: MIT
# Atlas KubeKit | By Atlas Richie
"""Synchronize standalone script version metadata from the repository VERSION file."""

import argparse
import os
from pathlib import Path
import re
import sys
import tempfile

ROOT = Path(__file__).resolve().parent.parent
VERSION_FILE = ROOT / "VERSION"
HEADER = "# Atlas KubeKit | By Atlas Richie\n"
BEGIN = "# BEGIN ATLAS KUBEKIT VERSION (generated by scripts/update-version.py)"
END = "# END ATLAS KUBEKIT VERSION"
NUMBER = r"(?:0|[1-9][0-9]*)"
PRERELEASE = r"(?:0|[1-9][0-9]*|[0-9A-Za-z-]*[A-Za-z-][0-9A-Za-z-]*)"
SEMVER = re.compile(
    rf"{NUMBER}\.{NUMBER}\.{NUMBER}"
    rf"(?:-{PRERELEASE}(?:\.{PRERELEASE})*)?"
    r"(?:\+[0-9A-Za-z-]+(?:\.[0-9A-Za-z-]+)*)?"
)
BLOCK_PATTERN = re.compile(re.escape(BEGIN) + r"\n.*?\n" + re.escape(END) + r"\n", re.S)


def version_block(version):
    return (
        f"{BEGIN}\n"
        f"ATLAS_KUBEKIT_VERSION='{version}'\n"
        'if [ "${1:-}" = --version ] || [ "${1:-}" = -V ]; then\n'
        '  printf \'Atlas KubeKit %s\\n\' "$ATLAS_KUBEKIT_VERSION"\n'
        '  exit 0\n'
        'fi\n'
        f"{END}\n"
    )


def atomic_write(path, text):
    mode = path.stat().st_mode & 0o777 if path.exists() else 0o644
    with tempfile.NamedTemporaryFile(mode="w", encoding="utf-8", dir=path.parent, delete=False) as temp:
        temporary = Path(temp.name)
        temp.write(text)
    try:
        temporary.chmod(mode)
        os.replace(temporary, path)
    finally:
        temporary.unlink(missing_ok=True)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("version", nargs="?", help="New SemVer value; omit to synchronize the current VERSION")
    parser.add_argument("--check", action="store_true", help="Check generated metadata without writing files")
    args = parser.parse_args()
    if args.check and args.version is not None:
        parser.error("--check cannot be combined with a new version")
    if VERSION_FILE.is_symlink():
        parser.error("VERSION must not be a symbolic link")
    version = args.version if args.version is not None else VERSION_FILE.read_text().strip()
    if SEMVER.fullmatch(version) is None:
        parser.error("Use SemVer without a v prefix, for example 0.1.0 or 0.2.0-rc.1")

    for name in ("01-prepare-node.sh", "02-deploy-cluster.sh", "03-install-addons.sh", "04-verify-cluster.sh"):
        if not (ROOT/name).is_file():
            parser.error(f"Missing entrypoint: {name}")
    stages = sorted((ROOT/"scripts/stages").glob("*.sh"))
    if not stages:
        parser.error("No internal stage scripts found; use the complete repository")
    scripts = sorted(ROOT.glob("*.sh")) + stages
    expected = version_block(version)
    updates = []
    missing = []
    for script in scripts:
        if script.is_symlink():
            parser.error(f"Script must not be a symbolic link: {script.relative_to(ROOT)}")
        content = script.read_text()
        blocks = BLOCK_PATTERN.findall(content)
        if len(blocks) == 1 and content.count(BEGIN) == 1 and content.count(END) == 1:
            replacement = BLOCK_PATTERN.sub(lambda _: expected, content, count=1)
        elif not blocks and BEGIN not in content and END not in content and content.count(HEADER) == 1:
            replacement = content.replace(HEADER, HEADER + expected, 1)
        else:
            parser.error(f"Missing project header or malformed version block: {script.relative_to(ROOT)}")
        if replacement != content:
            updates.append((script, replacement))
            missing.append(str(script.relative_to(ROOT)))

    if args.check:
        if missing:
            print("Version metadata is out of sync: " + ", ".join(missing), file=sys.stderr)
            return 1
        print(f"Atlas KubeKit {version}: version metadata matches in {len(scripts)} scripts")
        return 0
    # Validate and plan all changes before writing. No Git, system, or server operations.
    for script, content in updates:
        atomic_write(script, content)
    if args.version is not None:
        atomic_write(VERSION_FILE, version + "\n")
    print(f"Atlas KubeKit {version}: synchronized {len(scripts)} scripts ({len(updates)} changed)")
    return 0


if __name__ == "__main__":
    try:
        sys.exit(main())
    except OSError as exc:
        print(f"[ERROR] {exc}", file=sys.stderr)
        sys.exit(1)
